/**
 * GoogleSheetsDocument.java
 *
 * This file was generated by MapForce 2024.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.mapforce.GoogleSheets;



import com.altova.text.tablelike.ColumnSpecification;
import com.altova.text.tablelike.Header;
import com.altova.text.tablelike.ISerializer;
import com.altova.text.tablelike.csv.Table;
import com.altova.text.tablelike.csv.Serializer;

public class GoogleSheetsDocument extends Table {
	protected ISerializer createSerializer() {
		Serializer result= new Serializer(this,0);
		result.getFormat().setAssumeFirstRowAsHeaders(true);
		result.getFormat().setFieldDelimiter(',');
		
		result.getFormat().setQuoteCharacter('\"');
		
		result.getFormat().setRemoveEmpty(true);
		result.getFormat().setAlwaysQuote(0 == 1);
		return result;
	}
	protected void initHeader(Header header) {
		
		header.add(new ColumnSpecification("entryNumber"));
		header.add(new ColumnSpecification("lineNumber"));
		header.add(new ColumnSpecification("enteredBy"));
		header.add(new ColumnSpecification("enteredDate"));
		header.add(new ColumnSpecification("postingDate"));
		header.add(new ColumnSpecification("organizationIdentifier"));
		header.add(new ColumnSpecification("sourceJournalID"));
		header.add(new ColumnSpecification("sourceJournalDescription"));
		header.add(new ColumnSpecification("accountMainID"));
		header.add(new ColumnSpecification("accountMainDescription"));
		header.add(new ColumnSpecification("amount"));
		header.add(new ColumnSpecification("debitCreditCode"));
		header.add(new ColumnSpecification("identifierCode"));
		header.add(new ColumnSpecification("identifierDescription"));
		header.add(new ColumnSpecification("identifierType"));
		header.add(new ColumnSpecification("documentTypeDescription"));
		header.add(new ColumnSpecification("documentNumber"));
		header.add(new ColumnSpecification("documentDate"));
		header.add(new ColumnSpecification("measurableCode"));
		header.add(new ColumnSpecification("measurableID"));
		header.add(new ColumnSpecification("measurableDescription"));
		header.add(new ColumnSpecification("measurableQuantity"));
		header.add(new ColumnSpecification("measurableUnitOfMeasure"));
		header.add(new ColumnSpecification("measurableCostPerUnit"));
	}
	public GoogleSheetsDocument(com.altova.typeinfo.TypeInfo tableType,int lineend) {
		super( tableType,lineend);
	}
}



